spring:
   application:
      name: hello-server
server:
  port: 8071
eureka:
  instance:
    hostname: localhost  client:    register-with-eureka: true
    fetch-registry: true
    service-url: 
         defaultZone: http://localhost:8070/eureka/
    
            
        
        
  